[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairopen_contracts/src", "./lib/cairo_contracts/src", "./lib/bal7hazar_contracts/src", "src"]

[contracts]
CarbonableBadge = ["src/badge/badge.cairo"]
CarbonableProject = ["src/project/project.cairo"]
CarbonableMinter = ["src/mint/minter.cairo"]
CarbonableYielder = ["src/farm/yielder.cairo"]
CarbonableOffseter = ["src/farm/offseter.cairo"]

[test]
target = ["tests"]

[profile.devnet.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.deploy]
network = "testnet"

[profile.mainnet.deploy]
network = "mainnet"
