["protostar.config"]
protostar_version = "0.2.1"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src"]

["protostar.contracts"]
CarbonableProjectNFT = [
    "./src/nft/CarbonableProjectNFT.cairo",
]

CarbonableMinter = [
    "./src/mint/CarbonableMinter.cairo",
]

