[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairopen_contracts/src",
    "./lib/cairo_contracts/src",
    "./lib/cairo_erc_3525/src",
    "./lib/bal7hazar_contracts/src",
    "./lib/cairo_migrator/src",
    "./lib/starkvest/src",
    "src",
]

[contracts]
CarbonableBadge = ["src/badge/badge.cairo"]
CarbonableBadgeMinter = ["src/badge/minter.cairo"]
CarbonableProxy = ["src/proxy/proxy.cairo"]
CarbonableProject = ["src/project/project.cairo"]
CarbonableMinter = ["src/mint/minter.cairo"]
CarbonableVester = ["src/vesting/vester.cairo"]
CarbonableOffseter = ["src/offset/offseter.cairo"]
CarbonableYielder = ["src/yield/yielder.cairo"]

[test]
target = ["tests"]

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.project]
network = "testnet"
private-key-path = "./.env"
account-address = "0x063675fa1ecea10063722e61557ed7f49ed2503d6cdd74f4b31e9770b473650c"
block-explorer = "starkscan"

[profile.testnet2.project]
gateway-url = "https://alpha4-2.starknet.io"
chain-id = 1536727068981429685321
private-key-path = "./.env"
account-address = "0x063675fa1ecea10063722e61557ed7f49ed2503d6cdd74f4b31e9770b473650c"
block-explorer = "starkscan"

[profile.mainnet.project]
network = "mainnet"
