["protostar.config"]
protostar_version = "0.3.1"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src"]

["protostar.contracts"]
CarbonableProjectNFT = [
    "./src/nft/project/CarbonableProjectNFT.cairo",
]

CarbonableMinter = [
    "./src/mint/minter.cairo",
]

CarbonableYieldManager = [
    "./src/yield/yield_manager.cairo",
]

["protostar.test"]
target = ["tests"]

# https://github.com/Shard-Labs/starknet-devnet
[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"