[package]
name = "carbon"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.2.0"
alexandria_storage = { git = "https://github.com/tekkac/alexandria", branch = "feat/interpolation-fast" }
alexandria_numeric = { git = "https://github.com/tekkac/alexandria", branch = "feat/interpolation-fast" }
alexandria_data_structures = { git = "https://github.com/tekkac/alexandria", branch = "feat/interpolation-fast" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }
cairo_erc_3525 = { git = "https://github.com/carbonable-labs/cairo-erc-3525", tag = "2.0.10" }
cairo_erc_2981 = { git = "https://github.com/carbonable-labs/cairo-erc-2981", tag="v1.0.1" }

[[target.starknet-contract]]
