name: CI Tests

on: [push, pull_request, pull_request_target]

env:
  PROTOSTAR_VERSION: 0.13.0

jobs:
  protostar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash -s -- -v $PROTOSTAR_VERSION

      - name: Install protostar dependencies
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && make install

      - name: Compile smart contracts
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && make build

      - name: Run protostar tests
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && make test
